title: docker runx
description: >- # this means to ignore newlines until "baseurl:"
  docker run, better
theme: jekyll-theme-midnight
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
show_download: true
