title: docker runx
description: >- # this means to ignore newlines until "baseurl:"
  docker run, better
theme: jekyll-theme-leap-day
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false
