name: Release on tag

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up containerd
        uses: crazy-max/ghaction-setup-docker@v3
        with:
          set-host: true
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: Binaries
        run: task go:bin:all

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/docker-runx-*